create table usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    email varchar(160) not null unique,
    senha varchar(255) not null,
    perfil varchar(40) not null,
    ativo boolean not null default true
);

create table membros (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    telefone varchar(30),
    email varchar(160),
    data_entrada date,
    funcao varchar(40) not null,
    status varchar(40) not null,
    observacoes text
);

create table assistencias (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    entidade_consulta varchar(120),
    data_consulta date,
    cidade varchar(120),
    whatsapp varchar(30),
    observacoes text,
    status varchar(40) not null
);

create table assistencia_tratamentos (
    assistencia_id bigint not null,
    tipo_tratamento varchar(60) not null,
    constraint fk_assistencia_tratamentos_assistencia
        foreign key (assistencia_id) references assistencias (id) on delete cascade
);

create table sessoes_tratamento (
    id bigint generated by default as identity primary key,
    numero_sessao integer not null,
    data_sessao date not null,
    realizada boolean not null,
    observacoes text,
    assistencia_id bigint,
    constraint fk_sessoes_tratamento_assistencia
        foreign key (assistencia_id) references assistencias (id) on delete cascade
);

create table materiais (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    categoria varchar(60) not null,
    quantidade_atual integer not null,
    quantidade_minima integer not null,
    unidade_medida varchar(30) not null,
    local_armazenamento varchar(120),
    observacoes text
);

create table movimentacoes_estoque (
    id bigint generated by default as identity primary key,
    material_id bigint not null,
    tipo varchar(20) not null,
    quantidade integer not null,
    data_movimentacao date,
    responsavel varchar(120) not null,
    motivo varchar(160),
    observacoes text,
    constraint fk_movimentacoes_estoque_material
        foreign key (material_id) references materiais (id)
);

create table lancamentos_financeiros (
    id bigint generated by default as identity primary key,
    descricao varchar(160) not null,
    responsavel varchar(120),
    valor numeric(19, 2) not null,
    data_lancamento date not null,
    data_vencimento date,
    data_pagamento date,
    tipo varchar(20) not null,
    categoria varchar(60) not null,
    status varchar(40) not null,
    membro_id bigint,
    observacoes text,
    constraint fk_lancamentos_financeiros_membro
        foreign key (membro_id) references membros (id)
);

create index idx_usuarios_email on usuarios (email);
create index idx_assistencias_nome on assistencias (nome);
create index idx_assistencias_status on assistencias (status);
create index idx_materiais_categoria on materiais (categoria);
create index idx_lancamentos_status on lancamentos_financeiros (status);
create index idx_lancamentos_data_vencimento on lancamentos_financeiros (data_vencimento);
