create table auditorias (
    id bigint generated by default as identity primary key,
    criado_em timestamp not null,
    usuario_email varchar(160),
    usuario_nome varchar(120),
    modulo varchar(60) not null,
    acao varchar(60) not null,
    entidade varchar(80) not null,
    entidade_id bigint,
    descricao varchar(255) not null
);

create index idx_auditorias_criado_em on auditorias (criado_em);
create index idx_auditorias_modulo on auditorias (modulo);
create index idx_auditorias_usuario_email on auditorias (usuario_email);
